export const SET_CARD_TABLE_LAYOUT = 'SET_CARD_TABLE_LAYOUT';
export const SETUP_FOR_NEW_GAME = 'SETUP_FOR_NEW_GAME';
export const THROW_FOR_ACE = 'THROW_FOR_ACE';
export const RESOLVE_CARD_MOVEMENT = 'RESOLVE_CARD_MOVEMENT';
export const SELECTED_DEALER = 'SELECTED_DEALER';